name: $(DayOfYear)$(Rev:rr)_$(GITVERSION.FullSemVer)

variables:
- group: Cast

stages:
- stage: Build
  displayName: Build stage
  
  jobs:
  - job: Build
    displayName: Build
    pool : Cast
    timeoutInMinutes: 360
    
    steps:
    - checkout: self
    - script: echo "$(Build.SourcesDirectory)"
      displayName: 'Display Sources Directory of Azure agent working directory'
