name: $(DayOfYear)$(Rev:rr)_$(GITVERSION.FullSemVer)

trigger:
- master

variables:
- group: Agents
- group: Nuget
- name: BuildConfiguration
  value: 'release'
- name: verbosity
  value: 'detailed'

stages:
- stage: Build
  displayName: Build stage
  
  jobs:
  - job: Build
    displayName: Build
    pool : Cast
    timeoutInMinutes: 360

    steps:
    - checkout: self
    - checkout: git://Portfolio/CICD@$(CICDBranch)
        